### ISSUE TITLE
Stabilize vecmath

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/vecmath#227]
The design of this library has been tested and it seems to work very well with reexporting. It consists of global functions with a naming convention to support both column and row major matrices. The library uses arrays `[T; N]`.

One problem is the dependency on the `num` crate, which pulls in `libc`, `rand`, `log` and `rustc-serialize`. These libraries are not strictly needed for this library, and they might not get stabilized for a long time.

- [x] Make as many functions as possible use `std::ops` traits directly
- [x] Move to independent library for floats https://github.com/pistondevelopers/float

**Comment by bvssvni** [comment]
We could stabilize the things that are not depending on `num` crate and try replace the `Float` trait when not needed. Can also add some minimalistic traits and implement them for `f32` and `f64` to get rid of the remaining ones.

**Comment by stjahns** [comment]
Personally I'm not a huge fan of this, I think this solution is worse than the problem. I'm trying to fix camera_controllers, and now rather than just using num::Float I need to have hideous code like 

```
impl<T> FirstPerson<T>
    where T: Copy +
    FromPrimitive +
    Trig +
    Sqrt +
    Radians +
    One +
    Zero +
    Mul<T, Output = T> +
    Add<T, Output = T> +
    Sub<T, Output = T> +
    Div<T, Output = T> +
    Rem<T, Output = T> +
    Neg<Output = T>
{
    /// ...
```

while STILL needing to use num::FromPrimitive anyway  to convert delta times and mouse coordinates to T.  Also I need to add a another trait for `signum` to vecmath. I'm not sure like the idea of re-inventing almost all of `num` within vecmath. Maybe something just isn't clicking for me?

**Comment by bvssvni** [comment]
We discussed this on IRC and decided to add a `Float` trait to solve the problems with generic code.
