### ISSUE TITLE
Nothing implements math traits (`Add`, `Mul`, etc)

### ISSUE THREAD

**Issue by icefoxen** [PistonDevelopers/vecmath#277]

**Comment by sacherjj** [comment]
It looks like separate pub functions are used, instead of implementing traits, so that all those methods can be `#[inline(always)]`.   I don't believe there is a way to inline a trait.   I assume those testing found that this is much faster in operation.

The discussion could be made if both interfaces (implemented math traits) and faster ones should be offered.  The downside might be that users would not know the cost (if any) of not selecting the function method, rather than trait method.

**Comment by icefoxen** [comment]
Does `#[inline(always)]` actually make a difference?  In my experience, rustc is super aggressive about inlining at higher opt levels.

**Comment by sacherjj** [comment]
I'm too new in Rust to know.  However, Rust already has too many functions.  The only way is probably to do both and benchmark.

**Comment by sacherjj** [comment]
Actually, playing with this a little.  They are just all aliased arrays.  So you can't impl anything on them.   Feels like C, not Rust.

**Comment by bvssvni** [comment]
This library is designed for reexporting, not as a standalone math library. See the [README](https://github.com/PistonDevelopers/vecmath/blob/master/README.md).

Closing.
